### PR TITLE
Angular translate handler log strict DI support

### PR DESCRIPTION
**Pull request by tiblu**
Add strict DI support to Angular translate handler log (src/service/handler-log.js).

### CODE REVIEW

**Comment by knalli** [comment]
We do have explicit dependency naming, see in artifact https://github.com/angular-translate/bower-angular-translate-handler-log/blob/2.13.0/angular-translate-handler-log.js#L22

**Comment by tiblu** [comment]
It's there in the bower, but not in the source - https://github.com/angular-translate/angular-translate/blob/master/src/service/handler-log.js.

- How does it get added to the bower version?
- What's the consideration not having it straight up in the source code?

**Comment by knalli** [comment]
We apply additional code within the build process.

**Comment by tiblu** [comment]
Why in the build process, why not code it like you mean it? What's the benefit? Just out of curiosity.

**Comment by knalli** [comment]
Because it is not relevant for the code to run. It's an external request for minified code and eventually the strict di mode.

The source code is for maintenance and readability, but not for the build result.

There is no benefit including these optional code right into the source code -- unless the origin source code files would be released. And that's is not the case.

**Comment by tiblu** [comment]
OK, cool. Thanks for the insight and maintaining this great project!

**Comment by knalli** [comment]
Anyway: Thank you for sharing contribution ideas.

**Pull request closed without merging**
