### PR TITLE
refactor(service): Remove use of legacy methods on $http promises.

### PR DESCRIPTION
**Pull request by realityking**
Also saves a couple of lines of code.

### CODE REVIEW

**Comment by rafaelgondim** [comment]
This pull request fix some issues when using requests interceptors on $httpProvider. The interceptor can return new promisses that overrides the "success" and "error" callbacks

**Comment by realityking** [comment]
Any news on this? It' been a while.

**Comment by realityking** [comment]
The old methods are now deprecated: https://docs.angularjs.org/api/ng/service/$http

**Comment by knalli** [comment]
Looks fine, sorry for the delays.

**Comment by knalli** [comment]
Thank you again, landed as e7516dc

**Pull request closed without merging**
