### PR TITLE
Translation for Portuguese (brazil)

### PR DESCRIPTION
**Pull request by projenet**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **canary branch** (left side). Also you should start _your branch_ off _our canary_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
### Description

Please describe your pull request.

💔Thank you!

### CODE REVIEW

**Comment by projenet** [comment]
Portuguese translation

**Comment by projenet** [comment]
portuguese translation

**Comment by knalli** [comment]
@projenet  Thank you for starting Portuguese.

Before we can go deeper in this: If we will provide a Portuguese translation, we need all chapters to be translated -- not only the first one. :( Otherwise the users will not a full doc/guide.

Also a technical detail in Git/GitHub: As we describe in out Contribution Guidelines, you should start off the canary making a branch and then make a pull request to our canary.

**Comment by knalli** [comment]
Hello,

in part of a "Spring Cleaning 2017", we are closing this issue as part of several others. The meta discussion is available [here](https://github.com/angular-translate/angular-translate/issues/1671) for full transparency.

At the end, we are a small team and have only limited resources (both time and human) available. Said this, we must keep the focus and scope on the project.

We are grateful and appreciate to everyone for each made contribution (regardless being code, idea, documentation, and support).

We are deprecating/closing all issues which fulfills a specific set of criteria: mainly outdated, nice-to-have, or just out-of-scope.

----

Although the list has been curated to the best of our's knowledge, there will be some lack of understanding.

Okay, there a different stories behind all open issues, but we do not have the time for everything:

* Support: Because we have only limited resources, we cannot handle support questions any more. Please use appropriate boards like [Stackoverflow](http://stackoverflow.com/questions/tagged/angular-translate).
* Feature requests or ehancements: Altough it is probalbly a great idea (otherwise it would be closed already), we can not giving more resources to things out of scope or which are useful for too specific scenarios only.
* Bugs: Filed a long time ago, this bug either has a reasonable workaround, no effective solution without harming all others, or is lacking additional information/use-case.
* Docs: All documentation efforts not matching English will be abonded.

Thank you.

*angular-translate team*

----

# FAQ

**"But this is really important!"**

Well, we are all humans. Maybe we have overseen an important issue. If we missed something, we hope you are reaching as again *filing a new issue* with the reference to the old one. But please be aware: A bug without further details and a demo included will be rejected again.

**"But this would a great feature!"**

Reconsider: Are we really required to add something in order to make this feature happen? Or could you also create a project on your own utilizing this project?

**Pull request closed without merging**
