### PR TITLE
fix(service): remove recursive references during sanitization

### PR DESCRIPTION
**Pull request by dceddia**
Related to #1396

Replace recursive references with `undefined` rather than throwing an error.

### CODE REVIEW

**Comment by knalli** [comment]
Well, I'm not sure it is a good idea allowing "recursive object references". Putting this into a AJS scope will result into similar issues, too (due AJS' expression watchers). A well known object sample is a HTML element object which references itself in the children.parent references.

Said that, I have the following addtions:

1. Make the `undefined` result a opt-in feature (i.e. `$translateProvider.dontThrowExceptionOnSelfReferencingInterpolationParams(true) .. but shorter! :)).
2. Instead of resulting into an `undefined`, put at least an optional logging (i.e. `$log.warn(...)`).

**Comment by knalli** [comment]
@tspaeth wdyt?

**Comment by tspaeth** [comment]
I'm a bit far away from the topic itself. 
But with a bit reading into the issue, I'll agree that changing the behavior to undefined without a switch is somewhat a breaking change (I can't judge on the side effects just by reading... ). So I would also say: yup, at least as an opt-in feature / toggle.

**Comment by knalli** [comment]
Close this.

The thrown error is not acceptable and must be handled. We only catching the *already existing error* avoiding further escalation which results probably into undistinguishable error stack traces in a complete app.

**Pull request closed without merging**
