### PR TITLE
Spanish translation of the docs.

### PR DESCRIPTION
**Pull request by gonzalo-roberto-diaz**
Includes
1. the ngdocs themselves
2. edition of the .generate_site file
3. Spanish flag icon and entry in the Language dropdown

### CODE REVIEW

**Comment by knalli** [comment]
Thank you again, that looks awesome!

We'll have to change the commit messages slightly, but we can take care of this.

**Comment by gonzalo-roberto-diaz** [comment]
Jan,
 Anything wrong with my contribution? What kind of commit messages did you expect?
I am looking forward to contribute more, but it builds upon this!

Cheers

  Gonzalo

**Comment by gonzalo-roberto-diaz** [comment]
Jan, 

 Any news about merging my Spanish translation?
Do you need anything else for it to be good?

  Gonzalo

**Comment by knalli** [comment]
I'm quite busy currently. I'll try to pack the new stuff in the next days on canary. Thank you, and stay tuned.

**Comment by gonzalo-roberto-diaz** [comment]
Thanks! I am eager to contribute more stuff on top of it :)
Gonzalo

**Comment by knalli** [comment]
Thank you again! Landed as 142d0b3

**Pull request closed without merging**
