### PR TITLE
Include example on wildcards in registerAvailableLanguageKeys

### PR DESCRIPTION
**Pull request by atd**
Fixes angular-translate/angular-translate.github.io#9

### CODE REVIEW

**Comment by atd** [comment]
I searched for the right word :smile: 

That is how it is called in Wikipedia http://en.wikipedia.org/wiki/Locale

But RFC 5646 uses *region* http://tools.ietf.org/html/rfc5646#section-2.2.4

**Comment by tspaeth** [comment]
ISO 639 is more talking about "languages" and "macro languages"... mh.... so many options :-) http://en.wikipedia.org/wiki/ISO_639-3

region is also ok to me.

**Comment by knalli** [comment]
country + territory is correct in that term.

**Comment by knalli** [comment]
Thank you, landed as aeff411

**Pull request closed without merging**
