### PR TITLE
fix(directive): Make interpolate message format work smoothly also on me...

### LINKED ISSUE #789: Errors when using translate directive with dynamic value and messageformat pluralization
Please see the plunker example:
http://embed.plnkr.co/RhuPW6cqpfsSuBS1R45a/preview

As far as I understand it's because ```angular-translate.js``` tries to submit ```translate-values``` while those are not ready. ```messageformat.js ``` library receives empty values and throws an error.

### PR DESCRIPTION
**Pull request by tspaeth**
...ssage format > 0.1.7 - fixes #789 

This is an experimental patch for the issues mentioned on messageformat stuff - e.g. in #789

### CODE REVIEW

**Comment by knalli** [comment]
I think that is correct. Fine! :+1:

**Comment by tspaeth** [comment]
Hm. Just figured out, that this doesn't help on translate-values - just translate-value... 

and translate-values seems a bit harder.

The way should be: Wait, until all attributes have been parsed, then run interpolation and messageformat...

**Comment by tspaeth** [comment]
Didn't have time to update the PR yet... but for the impatient:
add 
```
       // initial setup
        if (iAttr.translateValues) {
          angular.extend(scope.interpolateParams, $parse(iAttr.translateValues)(scope.$parent));
        }
```

right here:
https://github.com/tspaeth/angular-translate/blob/canarycurrent/src/directive/translate.js#L127

**Comment by knalli** [comment]
Picked as 2533f2d, 887dc1b

**Pull request closed without merging**
