### PR TITLE
Prevent duplicate requests in partial loader

### PR DESCRIPTION
**Pull request by mtwar**
I updated the getTable function to chain subsequent calls off of the original HTTP request, passing through the value on success and reattempting the HTTP request on failure. This is pretty well described in my commit message.

### CODE REVIEW

**Comment by mtwar** [comment]
My commit list got a little messy from how I forked/updated this, but it's just my work in the diff :)

**Comment by mtwar** [comment]
I see I'm getting test failures because of the use of "this", but the original function also used "this" and I'm handling it correctly with closure scoping. Should I be concerned about this?

**Comment by knalli** [comment]
Do you think the check in jshint is incorrect?

**Comment by mtwar** [comment]
I refactored it, will resolve the test failures ASAP.

**Comment by mtwar** [comment]
@knalli this last test appears to be failing due to the intended behavioral change, which is that duplicate HTTP requests should not be made. The test is written assuming that five HTTP requests will be made for the three parts in its loader, whereas only three HTTP requests are now made. Should I just rewrite the test to account for this?

**Comment by knalli** [comment]
Well.

1. Please rebase your commits against the latest canary, and squash your commits into a single or so commit. 
2. Regarding the tests: I'm not in this topic right now, I've to have a deeper look. If you want you can add copies of the tests in question and apply the intended demo case.

**Pull request closed without merging**
