### PR TITLE
fix(docs): Fix typo in zh-cn docs.

### PR DESCRIPTION
**Pull request by wenzhixin**

### CODE REVIEW

**Comment by knalli** [comment]
Thank you, picked.

**Comment by wenzhixin** [comment]
https://github.com/angular-translate/angular-translate/blob/master/docs/content/guide/zh-cn/03_using-translate-service.ngdoc#L87

**Comment by knalli** [comment]
What do you mean?

**Comment by wenzhixin** [comment]
I mean this line: `$rooScope` is typo.

**Comment by knalli** [comment]
Perhaps you are confused because it's still only in `canary` (2a16eb65a6141a6d797d89013ddd32a9ddb744fa). Although you have make the PR to master, I'd picked it in canary right.

**Comment by wenzhixin** [comment]
OK, got it.

**Pull request closed without merging**
