### PR TITLE
fix(translate): handle null translation

### LINKED ISSUE #665: Null translations
Can we support null values in translations? For know:

``` javascript
  var translationMock = {
    'EXISTING_TRANSLATION_ID': 'foo',
    'BLANK_VALUE': '',
    'TRANSLATION_ID': 'Lorem Ipsum {{value}}',
    'TRANSLATION_ID_2': 'Lorem Ipsum {{value}} + {{value}}',
    'TRANSLATION_ID_3': 'Lorem Ipsum {{value + value}}',
    'NULL_TRANSLATION': null,
    'DOCUMENT': {
      'HEADER': {
        'TITLE': 'Header'
      },
      'SUBHEADER': {
        'TITLE': '2. Header'
      }
    }
  };

  describe('$translate', function () {
    it('should translate null values', function () {
      var deferred = $q.defer(),
          promise = deferred.promise,
          value;

      promise.then(function (translation) {
        value = translation;
      });

      $q.all([
        $translate("NULL_TRANSLATION")
      ]).then(function (translations) {
        deferred.resolve(translations);
      });

      $rootScope.$digest();
      expect(value[0]).toEqual('');
    });
  });
```

``` bash
Chrome 36.0.1985 (Linux) pascalprecht.translate $translate should translate null values FAILED
        TypeError: Cannot read property 'substr' of null
            at determineTranslation (/home/yanoo/Work/angular-translate/src/service/translate.js:1134:26)
            at $translate (/home/yanoo/Work/angular-translate/src/service/translate.js:781:11)
            at null.<anonymous> (/home/yanoo/Work/angular-translate/test/unit/service/translate.spec.js:277:9)
Chrome 36.0.1985 (Linux): Executed 251 of 251 (1 FAILED) (1.195 secs / 0.877 secs)
```

### PR DESCRIPTION
**Pull request by GuyMograbi**
null translation treated as if does not exist

fixes #665

### CODE REVIEW

**Comment by knalli** [comment]
Hello, 

thank you for this great contribution.

Technically, this PR is not ready as adding a feature for `$translate.instant(…)`, but not `$translate(…)`.

Additionally, I'm not sure if it would not be easier for you to create an own customer loader or post processor which removes null properties.

**Comment by GuyMograbi** [comment]
Thanks so much for pointing out I should add the same for $translate. done. 

Regarding your loader/processor comment - I just don't want translate to break. currently it breaks on null values. 
So I want to define some default behavior, and if someone wants to change that behavior they can use loaders and processors. 

Currently it feels too much like a bug.

But I admit this is a matter of taste.

**Comment by knalli** [comment]
Thank you, picked as 1e57b4f

**Comment by GuyMograbi** [comment]
Hi, what does that mean? Will is be accepted or is it rejected?

**Pull request closed without merging**
